#!/usr/bin/python3
# bpkg - A blendOS tool similar to the VanillaOS "apx" tool
# Created by SvGaming, 2023

import os
import sys
import yaml
import subprocess
from io import StringIO

version = "0.2.0"

def pkginstall():
    print("install placeholder")

def pkgremove():
    print("remove placeholder")

def pkgupdate():
    print("update placeholder")

def pkgsearch():
    print("search placeholder")

def usage():
    print("Usage:\nplaceholder\nAbout: bpkg by SvGaming for blendOS")

def main():
    if os.geteuid() != 0:
        print("\033[1m\033[31m>> e: \033[39mmust be run as root\033[0m")
        exit(-1)

    if os.path.exists("/etc/bpkg.yaml"):
        conf = open("/etc/bpkg.yaml", "r+")
    else:
        conf = open("/etc/bpkg.yaml", "w+")
        conf.write("# bpkg config file\n# Auto-generated by bpkg ")
        conf.write(version)
        conf.write("\n\ncontainers:\n  - name: <container name>\n    distro: <distro>\n    priority: 1")
        print("\033[1m\033[36m>> i: \033[39mThe bpkg config file located at \"/etc/bpkg.yml\" seems to be missing. A template file has been created.\033[0m")

    if len(sys.argv) < 2:
        print("\033[1m\033[31m>> e: \033[39minsufficient arguments\033[0m")
        usage()
        exit(1)
    
    if sys.argv[1] == "update":
        pkgupdate()
    elif sys.argv[1] == "search":
        pkgsearch()
    elif sys.argv[1] == "overwrite-config":
        print("\033[1m\033[36m>> i: \033[39moverwriting old config file with an autogenerated one\033[0m")
        conf.close()
        conf = open("/etc/bpkg.yaml", "w")
        conf.write("# bpkg config file\n# Auto-generated by bpkg ")
        conf.write(version)

        tmp = sys.stdout
        container_names = StringIO()
        container_images = StringIO()

        sys.stdout = container_names
        subprocess.run(['podman', 'ps', '-a', '--no-trunc', '--size', '--format', '.Names'])

        sys.stdout = container_images
        subprocess.run(['podman', 'ps', '-a', '--no-trunc', '--size', '--format', '.Images'])

        sys.stdout = tmp

        print(container_names.getvalue())
        print(container_images.getvalue())

        conf.write("\n\ncontainers:\n  - name: <container name>\n    distro: <distro>\n    priority: 1")
        conf.close()
        print("\033[1m\033[36m>> i: \033[39mdone, your new config file is located at \"/etc/bpkg.yaml\"\033[0m")
    else: 
        if len(sys.argv) < 3:
            print("\033[1m\033[31m>> e: \033[39minsufficient arguments for this operation or invalid operation\033[0m")
            usage()
            exit(1)
        if sys.argv[1] == "install":
            pkginstall()
        elif sys.argv[1] == "remove":
            pkginstall()
        else:
            print("\033[1m\033[31m>> e: \033[39minvalid operation\033[0m")
            usage()
            exit(1)
    


if __name__ == '__main__':
    main()